### ISSUE TITLE
add_foreign_key migrations failing

### ISSUE THREAD

**Issue by akostibas** [gobuffalo/fizz#9] opened 2018-07-19 02:48 UTC
After upgrading Pop & Fizz, I'm now receiving an error with migrations involving `add_foreign_key`. My migrations look like:

```
add_foreign_key("user", "station_id", {"stations": ["id"]}, {
  "on_delete": "SET NULL"
})
```

And when they attempt to run, I get the following error:
```
error processing ../migrations/20180411220843_test.up.fizz: could not fizz the migration ../migrations/20180411220843_test.up.fizz: line 12: expected next token to be ), got %> instead
make: *** [db_dev_migrate] Error 255
```

We're running a postgres database, if that makes any difference.

**Comment by stangah** [comment] 2018-07-20 00:19
This seems to specifically be caused by newlines near `{}` characters. Removing newlines in the above migration such that `{\n` and `\n}` don't show up in the last argument seems to fix it.

Maybe it's related to the new function syntax?

**Comment by cimnine** [comment] 2018-08-21 01:51
```
add_foreign_key("domains", "domain_id", {"domains": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE",
})
```

This is getting "fixed" to that:

```
add_foreign_key("domains", "domain_id", {"domains": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE",
}
```

But now the closing ")" is missing.

But if the syntax is like the following, all is well:

```
add_foreign_key("domains", "domain_id", {"domains": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE", })
```

**Comment by cimnine** [comment] 2018-08-21 02:02
The cause is this: https://github.com/gobuffalo/pop/issues/212

**Comment by stanislas-m** [comment] 2018-09-23 11:39
Fixed with https://github.com/gobuffalo/pop/pull/213

**Closed by stanislas-m** 2018-09-23 11:39 UTC
